import {
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  CircleHelp,
  Clipboard,
  ClipboardList,
  Code2,
  CreditCard,
  ExternalLink,
  Gamepad2,
  Gift,
  Github,
  Globe2,
  Home,
  Image,
  Layers3,
  Lock,
  Menu,
  Package,
  Palette,
  Receipt,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  Trophy,
  User,
  Users,
  X
} from "lucide-react";

export const Icons = {
  analytics: BarChart3,
  assets: Layers3,
  bell: Bell,
  book: BookOpen,
  box: Box,
  cart: ShoppingCart,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  close: X,
  code: Code2,
  collections: Box,
  copy: Clipboard,
  creditCard: CreditCard,
  docs: BookOpen,
  external: ExternalLink,
  game: Gamepad2,
  gift: Gift,
  github: Github,
  globe: Globe2,
  help: CircleHelp,
  home: Home,
  image: Image,
  lock: Lock,
  menu: Menu,
  orders: Receipt,
  package: Package,
  pages: ClipboardList,
  palette: Palette,
  products: ShoppingBag,
  receiz: ShieldCheck,
  rewards: Gift,
  search: Search,
  seal: ShieldCheck,
  settings: Settings,
  sliders: SlidersHorizontal,
  sparkle: Sparkles,
  star: Star,
  store: Store,
  trophy: Trophy,
  user: User,
  users: Users
};
